//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptNat
    {
        public int ANatId { get; set; }
        public string ANatNm { get; set; }
        public string ANatNmBng { get; set; }
        public string ANatShnm { get; set; }
        public string ANatShnmBng { get; set; }
        public bool AptFr { get; set; }
        public bool IsStaffDuty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
