//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNSystemType
    {
        public byte Systpid { get; set; }
        public Nullable<byte> PerTrDur { get; set; }
        public Nullable<byte> TYTrDur { get; set; }
        public Nullable<byte> OTrDur { get; set; }
        public Nullable<System.DateTime> LBNGenDt { get; set; }
        public Nullable<bool> NConRNm { get; set; }
        public Nullable<bool> NConBNm { get; set; }
        public Nullable<bool> NConNNm { get; set; }
        public Nullable<System.DateTime> LWkDt { get; set; }
        public Nullable<short> LnkId { get; set; }
        public Nullable<System.DateTime> LnkDt { get; set; }
        public Nullable<byte> TYDyDur { get; set; }
        public Nullable<bool> PerTrDurTp { get; set; }
        public Nullable<bool> TYTrDurTp { get; set; }
        public Nullable<bool> TYDyDurTp { get; set; }
        public Nullable<bool> OTrDurTP { get; set; }
        public Nullable<byte> CGTrDur { get; set; }
        public Nullable<bool> CGTrDurTp { get; set; }
        public Nullable<System.DateTime> LSearchDate { get; set; }
        public Nullable<int> LSearchId { get; set; }
        public string usrid { get; set; }
    }
}
