//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubCategory
    {
        public int CourseSubCategoryId { get; set; }
        public string Name { get; set; }
        public string NameBan { get; set; }
        public string ShortName { get; set; }
        public string ShortNameBan { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> BnListPriority { get; set; }
        public bool Trace { get; set; }
        public bool ANmCon { get; set; }
        public bool NmRGF { get; set; }
        public string Remarks { get; set; }
        public int CourseCategoryId { get; set; }
        public Nullable<bool> TransferProposal { get; set; }
        public string TpValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
