//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEducation
    {
        public long EducationId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> ExamCategoryId { get; set; }
        public Nullable<int> ExaminationId { get; set; }
        public Nullable<int> BoardId { get; set; }
        public Nullable<long> InstituteId { get; set; }
        public Nullable<int> Subjectid { get; set; }
        public string Roll { get; set; }
        public string RegNo { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> ResultGradeId { get; set; }
        public Nullable<double> Gpa { get; set; }
        public Nullable<double> Marks { get; set; }
        public string Distiction { get; set; }
        public string PassingYear { get; set; }
        public string CourseDuration { get; set; }
        public string OtherInstituteName { get; set; }
        public string OtherSubjectName { get; set; }
        public System.DateTime ResultPublishDate { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ResultText { get; set; }
        public string QResultCode { get; set; }
        public bool IsVarified { get; set; }
        public string ExamCategory { get; set; }
        public string Examination { get; set; }
        public string Board { get; set; }
        public string Institute { get; set; }
        public string SubjectName { get; set; }
        public string Result { get; set; }
        public Nullable<int> ExmCatId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> BrdId { get; set; }
        public Nullable<int> InstId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> RsltId { get; set; }
    }
}
