//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public int RankCategoryId { get; set; }
        public int OfficerTypeId { get; set; }
        public int CountryId { get; set; }
        public string ReferenceId { get; set; }
        public string PNo { get; set; }
        public string BnNo { get; set; }
        public string FullNameEng { get; set; }
        public string Name { get; set; }
        public string FullNameBan { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string BatchPosition { get; set; }
        public int GenderId { get; set; }
        public int RankId { get; set; }
        public int EmployeeStatusId { get; set; }
        public Nullable<int> SLCode { get; set; }
        public bool HasDollarSign { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateOfDollarSign { get; set; }
        public Nullable<int> TransferId { get; set; }
        public Nullable<int> Seniority { get; set; }
        public string NamingConv { get; set; }
        public string Notification { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ExecutionRemarkId { get; set; }
        public Nullable<System.DateTime> BExecutionDate { get; set; }
        public string BSpRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Active { get; set; }
    }
}
