//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStatus
    {
        public int EmployeeStatusId { get; set; }
        public string StatusTitle { get; set; }
        public string ShortTitle { get; set; }
        public int GCode { get; set; }
        public int SLCode { get; set; }
    }
}
