//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOpr
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public int OprRankId { get; set; }
        public int OccasionId { get; set; }
        public double OprGrade { get; set; }
        public string GradingStatus { get; set; }
        public Nullable<System.DateTime> OprFromDate { get; set; }
        public Nullable<System.DateTime> OprToDate { get; set; }
        public Nullable<int> RecomandationTypeId { get; set; }
        public string FileName { get; set; }
        public string ImageSec2 { get; set; }
        public string ImageSec4 { get; set; }
        public bool IsAdverseRemark { get; set; }
        public string AdverseRemark { get; set; }
        public string Section2 { get; set; }
        public string Section3 { get; set; }
        public string Section4 { get; set; }
        public Nullable<double> Overweight { get; set; }
        public Nullable<double> Underweight { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ApptRecom { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BOffCId { get; set; }
        public Nullable<int> AppoinmentId { get; set; }
        public string OtherAppointment { get; set; }
    }
}
