//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal
    {
        public int MedalId { get; set; }
        public string NameEng { get; set; }
        public string NameBan { get; set; }
        public string ShortNameEng { get; set; }
        public string ShortNameBan { get; set; }
        public int MedalType { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public bool C__ToTrace { get; set; }
        public bool ANmCon { get; set; }
        public bool NmRGF { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
