//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileNumber
    {
        public int Mobileid { get; set; }
        public string PNO { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Employeeid { get; set; }
    }
}
