//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BnoisDbContext : DbContext
    {
        public BnoisDbContext()
            : base("name=BnoisDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminFeedBack> AdminFeedBack { get; set; }
        public virtual DbSet<FlashNotice> FlashNotice { get; set; }
        public virtual DbSet<MobileNumber> MobileNumber { get; set; }
        public virtual DbSet<UserUpdateLog> UserUpdateLog { get; set; }
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AgeServicePolicy> AgeServicePolicy { get; set; }
        public virtual DbSet<AptCat> AptCat { get; set; }
        public virtual DbSet<AptNat> AptNat { get; set; }
        public virtual DbSet<AttributeType> AttributeType { get; set; }
        public virtual DbSet<Award> Award { get; set; }
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<BloodGroup> BloodGroup { get; set; }
        public virtual DbSet<BNSystemType> BNSystemType { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<BoardMember> BoardMember { get; set; }
        public virtual DbSet<BonusPtAward> BonusPtAward { get; set; }
        public virtual DbSet<BonusPtComApp> BonusPtComApp { get; set; }
        public virtual DbSet<BonusPtMedal> BonusPtMedal { get; set; }
        public virtual DbSet<BonusPtPublic> BonusPtPublic { get; set; }
        public virtual DbSet<BotherSisterInfo> BotherSisterInfo { get; set; }
        public virtual DbSet<BraCtryCoursePoint> BraCtryCoursePoint { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Certificate> Certificate { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Commendation> Commendation { get; set; }
        public virtual DbSet<CommissionType> CommissionType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseCategory> CourseCategory { get; set; }
        public virtual DbSet<CoursePoint> CoursePoint { get; set; }
        public virtual DbSet<CourseSubCategory> CourseSubCategory { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<DocumentUrl> DocumentUrl { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationPrevious> EducationPrevious { get; set; }
        public virtual DbSet<EffectType> EffectType { get; set; }
        public virtual DbSet<EmpEducation> EmpEducation { get; set; }
        public virtual DbSet<EmpLeaveDetail> EmpLeaveDetail { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeChildren> EmployeeChildren { get; set; }
        public virtual DbSet<EmployeeCourseFuturePlan> EmployeeCourseFuturePlan { get; set; }
        public virtual DbSet<EmployeeDollarSign> EmployeeDollarSign { get; set; }
        public virtual DbSet<EmployeeGeneral> EmployeeGeneral { get; set; }
        public virtual DbSet<EmployeeHajjDetail> EmployeeHajjDetail { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeave { get; set; }
        public virtual DbSet<EmployeeLeaveCountry> EmployeeLeaveCountry { get; set; }
        public virtual DbSet<EmployeeLeaveYear> EmployeeLeaveYear { get; set; }
        public virtual DbSet<EmployeeLpr> EmployeeLpr { get; set; }
        public virtual DbSet<EmployeeOpr> EmployeeOpr { get; set; }
        public virtual DbSet<EmployeeOther> EmployeeOther { get; set; }
        public virtual DbSet<EmployeePft> EmployeePft { get; set; }
        public virtual DbSet<EmployeePromotion> EmployeePromotion { get; set; }
        public virtual DbSet<EmployeeRank> EmployeeRank { get; set; }
        public virtual DbSet<EmployeeReport> EmployeeReport { get; set; }
        public virtual DbSet<EmployeeSecurityClearance> EmployeeSecurityClearance { get; set; }
        public virtual DbSet<EmployeeServiceExamResult> EmployeeServiceExamResult { get; set; }
        public virtual DbSet<EmployeeServiceExt> EmployeeServiceExt { get; set; }
        public virtual DbSet<EmployeeSport> EmployeeSport { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeTraining> EmployeeTraining { get; set; }
        public virtual DbSet<EmployeeTransferFuturePlan> EmployeeTransferFuturePlan { get; set; }
        public virtual DbSet<EmpRejoin> EmpRejoin { get; set; }
        public virtual DbSet<EmpRunMissing> EmpRunMissing { get; set; }
        public virtual DbSet<ExamCategory> ExamCategory { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<ExamSubject> ExamSubject { get; set; }
        public virtual DbSet<ExecutionRemark> ExecutionRemark { get; set; }
        public virtual DbSet<ExtraAppointment> ExtraAppointment { get; set; }
        public virtual DbSet<Extracurricular> Extracurricular { get; set; }
        public virtual DbSet<ExtracurricularType> ExtracurricularType { get; set; }
        public virtual DbSet<EyeVision> EyeVision { get; set; }
        public virtual DbSet<ForeignProject> ForeignProject { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HeirNextOfKinInfo> HeirNextOfKinInfo { get; set; }
        public virtual DbSet<HeirType> HeirType { get; set; }
        public virtual DbSet<Institute> Institute { get; set; }
        public virtual DbSet<InstituteType> InstituteType { get; set; }
        public virtual DbSet<LeavePolicy> LeavePolicy { get; set; }
        public virtual DbSet<LeavePurpose> LeavePurpose { get; set; }
        public virtual DbSet<LeaveType> LeaveType { get; set; }
        public virtual DbSet<LprCalculateInfo> LprCalculateInfo { get; set; }
        public virtual DbSet<MaritalType> MaritalType { get; set; }
        public virtual DbSet<Medal> Medal { get; set; }
        public virtual DbSet<MedalAward> MedalAward { get; set; }
        public virtual DbSet<MedicalCategory> MedicalCategory { get; set; }
        public virtual DbSet<MemberRole> MemberRole { get; set; }
        public virtual DbSet<MissionAppBranch> MissionAppBranch { get; set; }
        public virtual DbSet<MissionAppointment> MissionAppointment { get; set; }
        public virtual DbSet<MissionAppRank> MissionAppRank { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<Nomination> Nomination { get; set; }
        public virtual DbSet<NominationDetail> NominationDetail { get; set; }
        public virtual DbSet<NominationSchedule> NominationSchedule { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NSOfficeMapping> NSOfficeMapping { get; set; }
        public virtual DbSet<ObservationIntelligent> ObservationIntelligent { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<OfficeAppBranch> OfficeAppBranch { get; set; }
        public virtual DbSet<OfficeAppointment> OfficeAppointment { get; set; }
        public virtual DbSet<OfficeAppRank> OfficeAppRank { get; set; }
        public virtual DbSet<OfficerStream> OfficerStream { get; set; }
        public virtual DbSet<OfficerType> OfficerType { get; set; }
        public virtual DbSet<OfficeShipment> OfficeShipment { get; set; }
        public virtual DbSet<OprAptSuitability> OprAptSuitability { get; set; }
        public virtual DbSet<OprGrading> OprGrading { get; set; }
        public virtual DbSet<OprOccasion> OprOccasion { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Pattern> Pattern { get; set; }
        public virtual DbSet<PftResult> PftResult { get; set; }
        public virtual DbSet<PftType> PftType { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<PhysicalCondition> PhysicalCondition { get; set; }
        public virtual DbSet<PhysicalStructure> PhysicalStructure { get; set; }
        public virtual DbSet<PoorCourseResult> PoorCourseResult { get; set; }
        public virtual DbSet<PreCommissionCourse> PreCommissionCourse { get; set; }
        public virtual DbSet<PreCommissionCourseDetail> PreCommissionCourseDetail { get; set; }
        public virtual DbSet<PreCommissionRank> PreCommissionRank { get; set; }
        public virtual DbSet<PreviousExperience> PreviousExperience { get; set; }
        public virtual DbSet<PreviousLeave> PreviousLeave { get; set; }
        public virtual DbSet<PreviousMission> PreviousMission { get; set; }
        public virtual DbSet<PreviousPunishment> PreviousPunishment { get; set; }
        public virtual DbSet<PreviousTransfer> PreviousTransfer { get; set; }
        public virtual DbSet<PromotionBoard> PromotionBoard { get; set; }
        public virtual DbSet<PromotionNomination> PromotionNomination { get; set; }
        public virtual DbSet<PromotionPolicy> PromotionPolicy { get; set; }
        public virtual DbSet<ProposalCandidate> ProposalCandidate { get; set; }
        public virtual DbSet<ProposalDetail> ProposalDetail { get; set; }
        public virtual DbSet<PtDeductPunishment> PtDeductPunishment { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<PublicationCategory> PublicationCategory { get; set; }
        public virtual DbSet<PunishmentAccident> PunishmentAccident { get; set; }
        public virtual DbSet<PunishmentCategory> PunishmentCategory { get; set; }
        public virtual DbSet<PunishmentNature> PunishmentNature { get; set; }
        public virtual DbSet<PunishmentSubCategory> PunishmentSubCategory { get; set; }
        public virtual DbSet<QuickLink> QuickLink { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<RankCategory> RankCategory { get; set; }
        public virtual DbSet<RankMap> RankMap { get; set; }
        public virtual DbSet<RecomandationType> RecomandationType { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<Relative> Relative { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<ReligionCast> ReligionCast { get; set; }
        public virtual DbSet<Remark> Remark { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<ResultGrade> ResultGrade { get; set; }
        public virtual DbSet<ResultType> ResultType { get; set; }
        public virtual DbSet<RetiredAge> RetiredAge { get; set; }
        public virtual DbSet<RetiredEmpCertificate> RetiredEmpCertificate { get; set; }
        public virtual DbSet<RetiredEmpCountry> RetiredEmpCountry { get; set; }
        public virtual DbSet<RetiredEmployee> RetiredEmployee { get; set; }
        public virtual DbSet<SearchAdminAuthorityParams> SearchAdminAuthorityParams { get; set; }
        public virtual DbSet<SearchAppointmentCategoryParams> SearchAppointmentCategoryParams { get; set; }
        public virtual DbSet<SearchAppointmentParams> SearchAppointmentParams { get; set; }
        public virtual DbSet<SearchAppreciationParams> SearchAppreciationParams { get; set; }
        public virtual DbSet<SearchAreaTypeParams> SearchAreaTypeParams { get; set; }
        public virtual DbSet<SearchAwardParams> SearchAwardParams { get; set; }
        public virtual DbSet<SearchBatchParams> SearchBatchParams { get; set; }
        public virtual DbSet<SearchBloodGroupParams> SearchBloodGroupParams { get; set; }
        public virtual DbSet<SearchBranchParams> SearchBranchParams { get; set; }
        public virtual DbSet<SearchCategoryParams> SearchCategoryParams { get; set; }
        public virtual DbSet<SearchClearanceParams> SearchClearanceParams { get; set; }
        public virtual DbSet<SearchColumn> SearchColumn { get; set; }
        public virtual DbSet<SearchCommendationParams> SearchCommendationParams { get; set; }
        public virtual DbSet<SearchCommissionTypeParams> SearchCommissionTypeParams { get; set; }
        public virtual DbSet<SearchCountryParams> SearchCountryParams { get; set; }
        public virtual DbSet<SearchCourseCategoryDoingParams> SearchCourseCategoryDoingParams { get; set; }
        public virtual DbSet<SearchCourseCategoryDoneParams> SearchCourseCategoryDoneParams { get; set; }
        public virtual DbSet<SearchCourseCategoryNotDoneParams> SearchCourseCategoryNotDoneParams { get; set; }
        public virtual DbSet<SearchCourseCountryParams> SearchCourseCountryParams { get; set; }
        public virtual DbSet<SearchCourseDoingParams> SearchCourseDoingParams { get; set; }
        public virtual DbSet<SearchCourseDoneParams> SearchCourseDoneParams { get; set; }
        public virtual DbSet<SearchCourseNotDoneParams> SearchCourseNotDoneParams { get; set; }
        public virtual DbSet<SearchCourseSubCategoryDoingParams> SearchCourseSubCategoryDoingParams { get; set; }
        public virtual DbSet<SearchCourseSubCategoryDoneParams> SearchCourseSubCategoryDoneParams { get; set; }
        public virtual DbSet<SearchCourseSubCategoryNotDoneParams> SearchCourseSubCategoryNotDoneParams { get; set; }
        public virtual DbSet<SearchCurrentStatusParams> SearchCurrentStatusParams { get; set; }
        public virtual DbSet<SearchDistrictParams> SearchDistrictParams { get; set; }
        public virtual DbSet<SearchDoingCourseCountryParams> SearchDoingCourseCountryParams { get; set; }
        public virtual DbSet<SearchEducationSubjectParams> SearchEducationSubjectParams { get; set; }
        public virtual DbSet<SearchExamParams> SearchExamParams { get; set; }
        public virtual DbSet<SearchInstituteParams> SearchInstituteParams { get; set; }
        public virtual DbSet<SearchLeaveCountryParams> SearchLeaveCountryParams { get; set; }
        public virtual DbSet<SearchMedalParams> SearchMedalParams { get; set; }
        public virtual DbSet<SearchMedicalCategoryParams> SearchMedicalCategoryParams { get; set; }
        public virtual DbSet<SearchMissionCountryParams> SearchMissionCountryParams { get; set; }
        public virtual DbSet<SearchNotDoneCourseCountryParams> SearchNotDoneCourseCountryParams { get; set; }
        public virtual DbSet<SearchNotServedAppointmentParams> SearchNotServedAppointmentParams { get; set; }
        public virtual DbSet<SearchNotServedOfficeParams> SearchNotServedOfficeParams { get; set; }
        public virtual DbSet<SearchOccasionParams> SearchOccasionParams { get; set; }
        public virtual DbSet<SearchOfficeParams> SearchOfficeParams { get; set; }
        public virtual DbSet<SearchOfficerServiceParams> SearchOfficerServiceParams { get; set; }
        public virtual DbSet<SearchOprRankParams> SearchOprRankParams { get; set; }
        public virtual DbSet<SearchPhysicalStructureParams> SearchPhysicalStructureParams { get; set; }
        public virtual DbSet<SearchPromotionStatusParams> SearchPromotionStatusParams { get; set; }
        public virtual DbSet<SearchPublicationCategoryParams> SearchPublicationCategoryParams { get; set; }
        public virtual DbSet<SearchPublicationParams> SearchPublicationParams { get; set; }
        public virtual DbSet<SearchPunishmentCategoryParams> SearchPunishmentCategoryParams { get; set; }
        public virtual DbSet<SearchPunishmentSubCategoryParams> SearchPunishmentSubCategoryParams { get; set; }
        public virtual DbSet<SearchRankParams> SearchRankParams { get; set; }
        public virtual DbSet<SearchReligionCastParams> SearchReligionCastParams { get; set; }
        public virtual DbSet<SearchReligionParams> SearchReligionParams { get; set; }
        public virtual DbSet<SearchResult> SearchResult { get; set; }
        public virtual DbSet<SearchResultParams> SearchResultParams { get; set; }
        public virtual DbSet<SearchServingAppointmentParams> SearchServingAppointmentParams { get; set; }
        public virtual DbSet<SearchServingofficeParams> SearchServingofficeParams { get; set; }
        public virtual DbSet<SearchShipParams> SearchShipParams { get; set; }
        public virtual DbSet<SearchSubBranchParams> SearchSubBranchParams { get; set; }
        public virtual DbSet<SearchSubCategoryParams> SearchSubCategoryParams { get; set; }
        public virtual DbSet<SearchSubjectParams> SearchSubjectParams { get; set; }
        public virtual DbSet<SearchTrainingInstituteParams> SearchTrainingInstituteParams { get; set; }
        public virtual DbSet<SearchTransferAdminAuthorityParams> SearchTransferAdminAuthorityParams { get; set; }
        public virtual DbSet<SearchTransferAreaParams> SearchTransferAreaParams { get; set; }
        public virtual DbSet<SearchVisitCategoryParams> SearchVisitCategoryParams { get; set; }
        public virtual DbSet<SearchVisitCountryParams> SearchVisitCountryParams { get; set; }
        public virtual DbSet<SeaService> SeaService { get; set; }
        public virtual DbSet<SecurityClearanceReason> SecurityClearanceReason { get; set; }
        public virtual DbSet<SeniorityPosition> SeniorityPosition { get; set; }
        public virtual DbSet<ServiceExam> ServiceExam { get; set; }
        public virtual DbSet<ServiceExamCategory> ServiceExamCategory { get; set; }
        public virtual DbSet<ShipCategory> ShipCategory { get; set; }
        public virtual DbSet<Sibling> Sibling { get; set; }
        public virtual DbSet<SocialAttribute> SocialAttribute { get; set; }
        public virtual DbSet<SpecialAptType> SpecialAptType { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<Spouse> Spouse { get; set; }
        public virtual DbSet<SpouseForeignVisit> SpouseForeignVisit { get; set; }
        public virtual DbSet<StatusChange> StatusChange { get; set; }
        public virtual DbSet<StoreProcedure> StoreProcedure { get; set; }
        public virtual DbSet<SubBranch> SubBranch { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Suitability> Suitability { get; set; }
        public virtual DbSet<TerminationType> TerminationType { get; set; }
        public virtual DbSet<TpQualifyingCriteria> TpQualifyingCriteria { get; set; }
        public virtual DbSet<TraceBonusRpt> TraceBonusRpt { get; set; }
        public virtual DbSet<TraceCoursePoint> TraceCoursePoint { get; set; }
        public virtual DbSet<TraceCourseRpt> TraceCourseRpt { get; set; }
        public virtual DbSet<TraceOprRpt> TraceOprRpt { get; set; }
        public virtual DbSet<TracePenaltyRpt> TracePenaltyRpt { get; set; }
        public virtual DbSet<TracePftRpt> TracePftRpt { get; set; }
        public virtual DbSet<TraceSetting> TraceSetting { get; set; }
        public virtual DbSet<TrainingBranch> TrainingBranch { get; set; }
        public virtual DbSet<TrainingInstitute> TrainingInstitute { get; set; }
        public virtual DbSet<TrainingPlan> TrainingPlan { get; set; }
        public virtual DbSet<TrainingRank> TrainingRank { get; set; }
        public virtual DbSet<TrainingResult> TrainingResult { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<TransferProposal> TransferProposal { get; set; }
        public virtual DbSet<Upazila> Upazila { get; set; }
        public virtual DbSet<UsedReport> UsedReport { get; set; }
        public virtual DbSet<UsedStoreProcedure> UsedStoreProcedure { get; set; }
        public virtual DbSet<VisitCategory> VisitCategory { get; set; }
        public virtual DbSet<VisitSubCategory> VisitSubCategory { get; set; }
        public virtual DbSet<YearList> YearList { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
        public virtual DbSet<vwForeignVisit> vwForeignVisit { get; set; }
        public virtual DbSet<vwNomination> vwNomination { get; set; }
        public virtual DbSet<vwTransfer> vwTransfer { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<Download> Download { get; set; }
    
        public virtual ObjectResult<GetLeaveInfo_Result> GetLeaveInfo(string employeeID, Nullable<int> idFrom, Nullable<int> idTo)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var idFromParameter = idFrom.HasValue ?
                new ObjectParameter("IdFrom", idFrom) :
                new ObjectParameter("IdFrom", typeof(int));
    
            var idToParameter = idTo.HasValue ?
                new ObjectParameter("IdTo", idTo) :
                new ObjectParameter("IdTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeaveInfo_Result>("GetLeaveInfo", employeeIDParameter, idFromParameter, idToParameter);
        }
    }
}
