//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public int NominationId { get; set; }
        public int EnitityType { get; set; }
        public int EntityId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public bool WithoutTransfer { get; set; }
        public bool WithoutAppointment { get; set; }
        public Nullable<int> MissoinAppointmentId { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
