//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeniorityPosition
    {
        public int EmployeeId { get; set; }
        public string PNo { get; set; }
        public int RankId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> SeniorityDate { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> LieutenantDate { get; set; }
        public string BatchNo { get; set; }
        public string BatchPosition { get; set; }
    }
}
