//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialAptType
    {
        public int Id { get; set; }
        public string SpAptType { get; set; }
        public int Position { get; set; }
        public bool IsActive { get; set; }
    }
}
