//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProcedure
    {
        public int StoreProcedureId { get; set; }
        public string ProcedureName { get; set; }
        public string Description { get; set; }
        public string ModuleName { get; set; }
        public string ReportNumber { get; set; }
        public string ReportName { get; set; }
        public string ReportVerssionNumber { get; set; }
        public string CreatedDate { get; set; }
        public string CreatorName { get; set; }
    }
}
