//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCategoryId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public bool Prefix { get; set; }
        public bool Rank { get; set; }
        public bool Branch { get; set; }
        public bool SubBranch { get; set; }
        public bool Course { get; set; }
        public bool Medal { get; set; }
        public bool Award { get; set; }
        public bool Prefix2 { get; set; }
        public string NmConEx { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool BN { get; set; }
        public bool BNVR { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
