//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpQualifyingCriteria
    {
        public int KeyCode { get; set; }
        public string Particular { get; set; }
        public string PValue { get; set; }
        public Nullable<bool> XStatus { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AptCategoryId { get; set; }
        public Nullable<int> SerialNo { get; set; }
    }
}
