//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceBonusRpt
    {
        public int EmployeeId { get; set; }
        public int CommendationId { get; set; }
        public Nullable<int> AwardId { get; set; }
        public Nullable<int> MedalId { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public int PCount { get; set; }
        public int AType { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public string Title { get; set; }
        public Nullable<int> YearName { get; set; }
        public Nullable<double> Bonus { get; set; }
        public string Remarks { get; set; }
    }
}
