//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceCoursePoint
    {
        public Nullable<int> CourseCategoryId { get; set; }
        public string CourseCategory { get; set; }
        public double WtAllowd { get; set; }
        public double Marks { get; set; }
        public double WtObtained { get; set; }
        public string Remarks { get; set; }
        public string SN { get; set; }
        public string BrName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CountryType { get; set; }
        public Nullable<int> Serial { get; set; }
    }
}
