//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingPlan
    {
        public int TrainingPlanId { get; set; }
        public int CourseCategoryId { get; set; }
        public int CourseSubCategoryId { get; set; }
        public int CourseId { get; set; }
        public string CourseNo { get; set; }
        public int CountryType { get; set; }
        public int CountryId { get; set; }
        public int InstituteId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> MaxParticipant { get; set; }
        public bool IsPostponed { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<System.DateTime> PToDate { get; set; }
        public string Purpose { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string IsClosed { get; set; }
        public bool IsActive { get; set; }
        public string ERcd { get; set; }
        public string EBRcd { get; set; }
    }
}
