//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUpdateLog
    {
        public long UserupdateLogId { get; set; }
        public string PNo { get; set; }
        public string PreviousEmail { get; set; }
        public string Email { get; set; }
        public string PreviousPhoneNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserId { get; set; }
    }
}
