//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetNominationInfo
    {
        public int NominationId { get; set; }
        public int EnitityType { get; set; }
        public string Nomination { get; set; }
        public int EntityId { get; set; }
        public string MissionAppointment { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Remarks { get; set; }
    }
}
